[%
    T = {
        configure_1                                = "IntranetUserJS: Changes to search page - Configuration",
        configure_2                                = "Home",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; IntranetUserJS: Changes to search page &rsaquo; Configuration",
        configure_5                                = "ID of the report to be used:",
        configure_6                                = "Save configuration",
        configure_7                                = "Upgrade status",
        configure_8                                = "Plugin has never been upgraded.",
        viewjs_1                                   = "IntranetUserJS: Changes to search page",
        viewjs_2                                   = "&rsaquo; ChangesToSearchPage &rsaquo; View JS Tool",
    }
%]