[%
    T = {
        configure_1                                = "IntranetUserJS: Muutokset hakusivulle - Asetukset",
        configure_2                                = "Etusivu",
        configure_3                                = "Moduulit",
        configure_4                                = "&rsaquo; IntranetUserJS: Muutokset hakusivulle &rsaquo; Asetukset",
        configure_5                                = "Käytettävän raportin ID:",
        configure_6                                = "Tallenna asetukset",
        configure_7                                = "Päivityksen tila",
        configure_8                                = "Liitännäistä ei ole koskaan päivitetty.",
        viewjs_1                                   = "IntranetUserJS: Muutokset hakusivulle",
        viewjs_2                                   = "&rsaquo; ChangesToSearchPage &rsaquo; Näytä JS-työkalu",
    }
%]