[%
    T = {
        configure_1                                = "IntranetUserJS: Ändringar på söksidan - Konfiguration",
        configure_2                                = "Hem",
        configure_3                                = "Moduler",
        configure_4                                = "&rsaquo; IntranetUserJS: Ändringar på söksidan &rsaquo; Konfiguration",
        configure_5                                = "ID för rapporten som ska användas:",
        configure_6                                = "Spara konfiguration",
        configure_7                                = "Uppgraderingsstatus",
        configure_8                                = "Modulen har aldrig uppgraderats.",
        viewjs_1                                   = "IntranetUserJS: Ändringar på söksidan",
        viewjs_2                                   = "&rsaquo; ChangesToSearchPage &rsaquo; Visa JS-verktyg",
    }
%]